## S3 Housekeeping CronJob Configuration

debug: true

# Container image configuration
image:
  repository: public.ecr.aws/lambda/python
  tag: "3.11"
  pullPolicy: IfNotPresent


# CronJob scheduling configuration
cronJob:
  # Cron expression, runs daily at 8 AM by default
  schedule: "0 8 * * *"
  # Number of job history to retain
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  # Concurrency policy: Allow, Forbid, Replace
  concurrencyPolicy: Forbid
  # Restart policy
  restartPolicy: OnFailure

# Resource limits
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Additional environment variables (optional)
envs:
  # Example: AWS_CA_BUNDLE for custom CA certificates
  # AWS_CA_BUNDLE:
  #   value: "/etc/ssl/certs/ca-bundle.crt"
  # LOG_LEVEL:
  #   value: "INFO"

# S3 configuration
s3:
  # List of buckets to monitor
  buckets:
    - name: "my-s3-bucket-1"
      lifecycleConfigName: "bucket1-lifecycle"
      # S3 credentials for this bucket
      accessKeyId:
        secretName: "s3-housekeeping-secret"
        secretKey: "AWS_ACCESS_KEY_ID"
      secretAccessKey:
        secretName: "s3-housekeeping-secret"
        secretKey: "AWS_SECRET_ACCESS_KEY"
      # S3 endpoint for this bucket
      endpoint: "https://s3.amazonaws.com"
      # Optional: CA Bundle path for this bucket
      # caBundle: "/path/to/ca-bundle.pem"
    - name: "my-s3-bucket-2"
      lifecycleConfigName: "archive-lifecycle"
      # Different S3 credentials for this bucket
      accessKeyId:
        secretName: "s3-housekeeping-secret-2"
        secretKey: "ACCESS_KEY"
      secretAccessKey:
        secretName: "s3-housekeeping-secret-2"
        secretKey: "SECRET_KEY"
      endpoint: "https://s3.amazonaws.com"
    # Add more buckets as needed
    # - name: "my-s3-bucket-3"
    #   lifecycleConfigName: "backup-lifecycle"
    #   accessKeyId:
    #     secretName: "s3-housekeeping-secret-3"
    #     secretKey: "aws_access_key_id"
    #   secretAccessKey:
    #     secretName: "s3-housekeeping-secret-3"
    #     secretKey: "aws_secret_access_key"
    #   endpoint: "https://custom-s3.example.com"
    #   caBundle: "/path/to/ca-bundle.pem"

# S3 lifecycle configuration
s3LifecycleConfigs:
  - name: "bucket1-lifecycle"
    content: |
      {
        "Rules": [
          {
            "ID": "temp-cleanup",
            "Status": "Enabled",
            "Filter": {
              "Prefix": "temp/"
            },
            "Expiration": {
              "Days": 7
            }
          },
          {
            "ID": "logs-cleanup",
            "Status": "Enabled",
            "Filter": {
              "Prefix": "logs/"
            },
            "Expiration": {
              "Days": 30
            }
          }
        ]
      }

  - name: "archive-lifecycle"
    content: |
      {
        "Rules": [
          {
            "ID": "archive-cleanup",
            "Status": "Enabled",
            "Filter": {
              "Prefix": "archive/"
            },
            "Expiration": {
              "Days": 365
            }
          }
        ]
      }
