apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3-housekeeping.fullname" . }}-script
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "s3-housekeeping.labels" . | nindent 4 }}
data:
  s3_lifecycle_manager.py: {{ .Files.Get "scripts/s3_lifecycle_manager.py" | quote }}
---
{{- if .Values.s3LifecycleConfigs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3-housekeeping.fullname" . }}-lifecycle-configs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "s3-housekeeping.labels" . | nindent 4 }}
data:
  {{- range .Values.s3LifecycleConfigs }}
  {{ .name }}.json: |
    {{- .content | nindent 4 }}
  {{- end }}
{{- end }}